Paginacao/it03/r23
yarion1/Front-Ps pull request #13
Opened 2022-04-24 19:39 UTC by nsouthomas

finalização da paginação e da lista de produtos

2022-04-25 11:08 UTC, edmilhomem commented
Recebi um feedback de que vc tinham mudado o padrão para usar o "r" na identificação do requisito "r23" para "R", conforme uma orientação anterior.

2022-04-25 13:07 UTC, Luanatvrs reviewed
Apenas mudar a pasta pagination para a pasta components, já que a paginação é um componente.

2022-04-27 23:42 UTC, Luanatvrs requested changes
.

2022-04-29 01:03 UTC, Luanatvrs approved these changes
Agora sim, tudo certo!

2022-04-30 23:42 UTC, CarlosEduViLi approved these changes
Muito bem produzido, aceito sem resalvas.

2022-05-08 23:52 UTC, merged