Perfildosprofissionais/IT04/R33
yarion1/Front-Ps pull request #35
Opened 2022-05-28 15:49 UTC by arthurffreis

Página e componentes referentes ao perfil dos trabalhadores da aplicação.

2022-05-28 16:00 UTC, yarion1 approved these changes
Revisado e aprovado

2022-05-28 17:57 UTC, Luanatvrs requested changes
Não coloque "_" no nome, coloque o padrão dos outros como por exemplo, em vez de "worker_profile" coloque "WorkerProfile", "StyledWorkerProfile" fica mais organizado.

2022-05-30 14:24 UTC, Luanatvrs approved these changes
Ok.

2022-05-30 14:38 UTC, merged

2022-05-30 14:39 UTC, marcosgilmario commented
- Conflitos resolvidos
- Branch mergida e deletada