Cadastro profissionais/it04/r44
yarion1/Front-Ps pull request #36
Opened 2022-05-28 16:01 UTC by yarion1

subindo upload de arquivos para validacao de profissionais

2022-05-28 16:10 UTC, arthurffreis approved these changes
Tudo Ok.

2022-05-28 16:17 UTC, arthurffreis commented
adicione seu nome em "assignees"

2022-05-28 18:01 UTC, Luanatvrs requested changes

2022-05-28 18:51 UTC, marcosgilmario requested changes
Revisar nomes das classes nos arquivos de componentes

2022-05-28 18:51 UTC, marcosgilmario commented on src/pages/upload/up.js
> +class App extends Component {
- Modificar no arquivo up.js o nnome da class para evitar redundancia no mapeamento de rotas e importações

2022-05-28 20:00 UTC, yarion1 commented on src/pages/upload/up.js
> +class App extends Component {
revisado!

2022-05-29 17:32 UTC, marcosgilmario approved these changes
Aprovado.

2022-05-29 18:06 UTC, Luanatvrs approved these changes
Aprovado.

2022-05-30 14:43 UTC, merged

2022-05-30 14:43 UTC, marcosgilmario commented
- Conflitos resolvidos
- Branch mergida e deletada