RefatoracaoDesignProdutos/IT05/R58
yarion1/Front-Ps pull request #42
Opened 2022-06-05 12:59 UTC by Luanatvrs

2022-06-05 13:12 UTC, arthurffreis requested changes
Corrigir o tamanho do botão.

2022-06-05 18:09 UTC, nsouthomas reviewed
corrigir o botão

2022-06-05 18:09 UTC, nsouthomas requested changes
botão

2022-06-09 18:57 UTC, nsouthomas requested changes
mudar background do botao e do preço pra msm cor da navbar, e quando eu mexo no zoom da pag ta aparecendo uma scrollbar no preço

2022-06-12 14:31 UTC, arthurffreis approved these changes
aprovado

2022-06-12 16:24 UTC, nsouthomas approved these changes

2022-06-12 20:17 UTC, closed without merging