Atualizaçãohomepage/IT05/R57
yarion1/Front-Ps pull request #46
Opened 2022-06-10 16:58 UTC by arthurffreis

Atualização da home page. Novos componentes e realinhamento com a nova identidade visual.

2022-06-10 18:34 UTC, nsouthomas requested changes
tirar o sublinhado e centralizar os botoes

2022-06-12 13:57 UTC, Luanatvrs requested changes
Resolver conflitos.

2022-06-12 16:25 UTC, nsouthomas approved these changes

2022-06-12 16:37 UTC, Luanatvrs approved these changes

2022-06-12 16:38 UTC, merged