Listas de produtos/it03/r08
yarion1/Front-Ps pull request #8
Opened 2022-04-18 03:27 UTC by nsouthomas

Deixei o layout responsivo e criei o inicio da paginação

2022-04-18 14:05 UTC, Luanatvrs approved these changes
FIcou bom, mas ao decorrer do projeto a gente vai melhorando ele.

2022-04-18 14:05 UTC, yarion1 approved these changes
Aprovado, espero que continue e termine o resto da paginação!

2022-04-18 14:49 UTC, arthurffreis approved these changes
Aprovado.

2022-04-18 14:52 UTC, marcosgilmario requested changes
- Necessário resolver os conflitos

2022-04-19 00:47 UTC, marcosgilmario approved these changes

2022-04-19 00:47 UTC, merged

2022-04-19 00:48 UTC, marcosgilmario commented
Branch mergida e deletada